### ISSUE TITLE
Amount is required, please verify and try again.

### ISSUE THREAD

**Issue by AkramChauhan** [apvanlaan/laravel-usaepay#9]
Everything works fine but getting "amount is required, please verify and try again."  when calling createSale Method in Sandbox.
As well as Transaction type not allowed from this source in each and every request.

Not sure why.

**Comment by apvanlaan** [comment]
@AkramChauhan 

First off thanks for trying out my package, hopefully once past these issues it will be helpful to your project.

Just to cover obvious bases , make sure you're passing/setting an amount or transaction_key in whichever manner you've chosen to use (feel free to paste a code snippet and I can see if I can sus out what might be the cause).  

Next, I've experienced some weird behaviors with the api in regards to the sandbox.  Try changing your EPAY_SUB to secure instead of sandbox, even if you're using a sandbox account api key and see if that allows the transactions to go through.  

Let me know if I can help more

Aaron
